package com.gerayking.gerayoj.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rank_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private Integer rankNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ac_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private Integer acNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.submit_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private Integer submitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rank_num
     *
     * @return the value of user.rank_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public Integer getRankNum() {
        return rankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rank_num
     *
     * @param rankNum the value for user.rank_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setRankNum(Integer rankNum) {
        this.rankNum = rankNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ac_num
     *
     * @return the value of user.ac_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public Integer getAcNum() {
        return acNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ac_num
     *
     * @param acNum the value for user.ac_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setAcNum(Integer acNum) {
        this.acNum = acNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.submit_num
     *
     * @return the value of user.submit_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public Integer getSubmitNum() {
        return submitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.submit_num
     *
     * @param submitNum the value for user.submit_num
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setSubmitNum(Integer submitNum) {
        this.submitNum = submitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue Oct 20 17:42:46 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}